### ISSUE TITLE
DK Starting Zone Bug

### ISSUE THREAD

**Issue by LKArthas** [cooler-SAI/TER-Server#20]
I finally got the server now cooler, and when create the DK for testing every time that i tryed to log in my client gives me wow error, i must have the same client in the code, or just my 4.3.4 rev15595, i got tha realm languaje problem but fixed changing from 12 (ru) to 1 (dev, any languaje) my wow client is in Spanish Latinoamerican, but a lot of the text in game still appearing in Russian, and change the world config and the realm in auth table

**Comment by cooler-SAI** [comment]
Realm Written nside the core auth code

**Comment by ter884** [comment]
1. crash at start
##FAN-BLIZZLAIK-CLIENT (без модификации клиента, КРЕШ)
TER-Server_FAN_ACHIVEMENT_SPELL_VALUTA = 0

2.source code, language in game

3.TER-Server-W.conf
RealmZone = 1
DBC.Locale = 255

**Comment by LKArthas** [comment]
forgot about the DBC Locale, already changed, but the DK problem Still persists i create a DK and gives me wow error when i try load it, and DBC.locale is set to 255 and for example the Starting zone for humans keeps me yelling in russian, and when it sets to 0 (English) still gives me the yells on Russian, but DKs keep giving me the same issue wow error every time i created one. :(

**Comment by ter884** [comment]
crash at start ##FAN-BLIZZLAIK-CLIENT (без модификации клиента, КРЕШ) TER-Server_FAN_ACHIVEMENT_SPELL_VALUTA = 0

**Comment by ter884** [comment]
"tarting zone for humans keeps me yelling in russian, and when it sets to 0 (English) still gives me the yells on Russian"

Table 
creature_text

**Comment by LKArthas** [comment]
got it fixed when i changed the dbc folder to the old one from wowsource but with the TER original dbc keeps giving me the wow error :/
