### ISSUE TITLE
prblem to login

### ISSUE THREAD

**Issue by warlokowla** [cooler-SAI/TER-Server#24]
I have a problem when entering the server says "those attempting to enter a realm of different language"

**Comment by LKArthas** [comment]
Please argument your issue, maybe you just need to change the realmzone in the auth database, and in the TER-Server-W.conf

**Comment by warlokowla** [comment]
in that part of the database auth modified?

**Comment by LKArthas** [comment]
realmlist, timezone column

**Comment by warlokowla** [comment]
change to 0 or?

**Comment by LKArthas** [comment]
1

**Comment by warlokowla** [comment]
thanks bro  :dancer:

**Comment by LKArthas** [comment]
no problem, did you fix it?

**Comment by warlokowla** [comment]
I have already arranged, thanks haora a problem with commands gm

**Comment by LKArthas** [comment]
i'm more worry about your wow client will give you a wow error when a command is pulled in
