### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by warlokowla** [cooler-SAI/TER-Server#32]
Hello, I have already started the server, I have given my range gm account (level 4) but I can not use the command says "there is not Such subcommand"

**Comment by warlokowla** [comment]
ERROR Table `command` have not existed subcommand 'trinity_string' in command 'reload trinity_string', skip.

**Comment by LKArthas** [comment]
did you try with a level 3 range? ----> account set gmlevel (Lkarthas) 3 -1

**Comment by warlokowla** [comment]
dont work :(

**Comment by cooler-SAI** [comment]
all works good, chech Realm Id forgm account

**Comment by ter884** [comment]
rbac_account_permissions  permissionId=47, rbac_account_groups groupId 4
