### ISSUE TITLE
Guild vendor Npc Dont work

### ISSUE THREAD

**Issue by warlokowla** [cooler-SAI/TER-Server#38]
Goram NPC not working ID: 46572

http://es.wowhead.com/npc=46572/goram

**Comment by LKArthas** [comment]
It seems to be wrongly handled by the core, i duplicated the creature, assigned a new ID, and update all entrys
---this is a patch fix not the real one---
UPDATE `npc_vendor` SET `entry`=465720 WHERE `entry`=46572;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `currencyId`, `currencyCount`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `WDBVerified`) VALUES (465720, 0, 0, 0, 0, 0, 35148, 0, 0, 0, 'Goram', 'Guild Vendor', '', 0, 45, 45, 0, 0, 1735, 1735, 129, 1, 1.14286, 1, 1.14286, 1, 0, 76, 100, 0, 184, 1, 2000, 2000, 1, 0, 2048, 2048, 0, 0, 0, 0, 0, 52, 76, 17, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, '', 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, '', 13623);
UPDATE `creature` SET `id`=465720 WHERE `id`=46572;
