### ISSUE TITLE
Curtail the Darktail (Blasted Lands)

### ISSUE THREAD

**Issue by LKArthas** [cooler-SAI/TER-Server#40]
---curtail the darktail---

---Linked Spell Missing----
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `req_aura`, `comment`) VALUES (78838, 78834, 0, 0, 'Enohar Flaming Arrow trigger');

---Script----
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42235, 0, 2, 3, 8, 0, 100, 0, 78834, 0, 0, 0, 51, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Darktail Bonepicker on Spellhit - Die');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42235, 0, 3, 0, 61, 0, 100, 0, 0, 0, 0, 0, 33, 42235, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Darktail Bonepicker on Spellhit - Give Credit');

**Comment by cooler-SAI** [comment]
please edit this patch
