### ISSUE TITLE
WoW error to teleport stormwind

### ISSUE THREAD

**Issue by warlokowla** [cooler-SAI/TER-Server#42]
wow error to teleport stormwind ".tele stormwind"

**Comment by ter884** [comment]
![default](https://cloud.githubusercontent.com/assets/6825541/11538966/a0665de0-9935-11e5-8048-e36101bec54c.PNG)
![2](https://cloud.githubusercontent.com/assets/6825541/11538967/a0b62668-9935-11e5-8638-1751fcb57eba.PNG)
![56](https://cloud.githubusercontent.com/assets/6825541/11538980/b75d7cae-9935-11e5-927d-33f2a5d88bed.PNG)
