### ISSUE TITLE
wow error in durotar zone

### ISSUE THREAD

**Issue by warlokowla** [cooler-SAI/TER-Server#43]
wow error in durotar zone, before it leaves the error NPC "unknown entity

**Comment by ter884** [comment]
![default](https://cloud.githubusercontent.com/assets/6825541/11539028/ffc3e834-9935-11e5-85db-70c8c8a38a98.PNG)
![2](https://cloud.githubusercontent.com/assets/6825541/11539049/2a4e93e2-9936-11e5-98b1-a339945a2188.PNG)
