### ISSUE TITLE
kick server

### ISSUE THREAD

**Issue by warlokowla** [cooler-SAI/TER-Server#46]
http://oi67.tinypic.com/rrsfet.jpg

http://oi68.tinypic.com/r0nx8m.jpg

2015-12-03_03:56:09 ERROR [1264] Out of range value for column 'max' at row 1
2015-12-03_03:56:09 ERROR Unhandled MySQL errno 1264. Unexpected behaviour possible.

the server gets me every so often, i nedd fix this problem :(

**Comment by ter884** [comment]
debug log

**Comment by ter884** [comment]
can expect you using the new kernel on older tables

**Comment by warlokowla** [comment]
im use release :(

**Comment by warlokowla** [comment]
DROP TABLE IF EXISTS `character_skills`;
CREATE TABLE `character_skills` (
  `guid` int(10) unsigned NOT NULL COMMENT 'Global Unique Identifier',
  `skill` smallint(5) unsigned NOT NULL,
  `value` smallint(5) unsigned NOT NULL,
  `max` smallint(10) unsigned NOT NULL,
  PRIMARY KEY (`guid`,`skill`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Player System';


this is a temporary solution that did
execute sql query in char DB

**Comment by warlokowla** [comment]
DROP TABLE IF EXISTS character_skills;
CREATE TABLE character_skills (
guid int(10) unsigned NOT NULL COMMENT 'Global Unique Identifier',
skill smallint(5) unsigned NOT NULL,
value smallint(5) unsigned NOT NULL,
max smallint(10) unsigned NOT NULL,
PRIMARY KEY (guid,skill)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Player System';

this is a temporary solution that did
execute sql query in char DB
