### ISSUE TITLE
World Error in latest build

### ISSUE THREAD

**Issue by justinpierson** [cooler-SAI/TER-Server#47]
Thank you for a fantastic server!
Pulled down the latest code (12/15) built with visual studio 2013, rebuilt the database applying the updates and when I run the world it crashes after a few seconds:

Ter-Server 4.3.4\TER-Server-master\src\server\game\Entities\Item\Item.cpp:680 in Item:
:AddToUpdateQueueOf ASSERTION FAILED:
  player != NULL
[0x2f84a3]
[0x472d4d]
[0x476a77]
[0x28e84b]
[0x229b3]
[0xbcde]
[0x4ce0cf]
ACE_OS_Thread_Adapter::invoke()+0x7a [0x6047a]
beginthreadex()+0x107 [0x24f7f]
endthreadex()+0x192 [0x25126]
BaseThreadInitThunk()+0x22 [0x13d2]
RtlUserThreadStart()+0x34 [0x15454]

Any ideas?

**Comment by cooler-SAI** [comment]
turn Off AuctionHouseBot Seller anb Buyer in config, Run the server, then off and turn On
sometimes this error happens, when server turned off few days
