### ISSUE TITLE
Pet not attacking

### ISSUE THREAD

**Issue by justinpierson** [cooler-SAI/TER-Server#48]
Hunter/Warlock pet is not attacking when set to defensive and autoshot/spell is used.

**Comment by ter884** [comment]
vmaps included?

**Comment by ter884** [comment]
your level more than 10?

**Comment by justinpierson** [comment]
Yes I am using vmaps, I have tried leveling past 10 and its the same behavior:
1. Cast a spell with a warlock and the pet does nothing until you are hit, which by the code should not be happening (they should attack as soon as you start casting a damaging spell)
2. When you autoshoot as a hunter your pet should start attacking immediately.

I have checked with this other releases (wowsource 434 10 is broken as well) and it works.

**Comment by justinpierson** [comment]
I think I found the problem... in petAI.cs -> void PetAI::OwnerAttacked(Unit* target)

I changed:
// Passive pets don't do anything
	if (!me->HasReactState(REACT_ASSIST))
		return;
To
// Passive pets don't do anything
	if (me->HasReactState(REACT_PASSIVE))
		return;

Which when I thought about it made more sense, and do the pets in 4.4.3 have assist mode anymore, since its called defensive now? Regardless this will have the pet attack when you attack if they are any mode other then passive.

**Comment by ter884** [comment]
try
commit :: 118acc1fcd3333fb82c07093e1effeaac36a4474
