### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by adsprosto** [cooler-SAI/TER-Server#52]
lots of errors with start server
for example:
ERROR Creature template (Entry: 99997) does not exist but has a record in `creature_equip_template`

**Comment by ter884** [comment]
in her 3 DB Ter-Server_DB_CATA_r400+YTDB720+ArkDB+15000 smart scripts, there are also duplicates, you name that is known to all of us, I think it's hard not to see these errors at startup, but they do not interfere with the game

**Comment by adsprosto** [comment]
but I would like to repair this for simplicity

**Comment by ter884** [comment]
this error is nothing dangerous, you have the equipment for creatures that don't exist, if it bothers you then delete that entry from the table
