### ISSUE TITLE
Not Auth to server

### ISSUE THREAD

**Issue by adsprosto** [cooler-SAI/TER-Server#54]
ERROR WorldSocket::HandlePing: [Player: <none> (Guid: 0, Account: 60)] kicked for over-speed pings (address: 109.94.19.35)
after this error in core the "connection is established" and crash

**Comment by ter884** [comment]
поставить пинг в конфигурации выше или вы воспользовались .изменение скорости х без доступа уровня

**Comment by adsprosto** [comment]
ok
