### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by adsprosto** [cooler-SAI/TER-Server#55]
При входе на персонажа которого только что создал происходит краш сервера
С чем может быть связано?

**Comment by ter884** [comment]
уточните за какую расу и класс персонаж создан, (креш наблюдается в данном случаи токо за тролей)

**Comment by adsprosto** [comment]
происходит именно даже не краш клиента а краш самого ядра
вход производится за любую расу и класс

**Comment by adsprosto** [comment]
в дебаге все в порядке - немного странно

**Comment by cooler-SAI** [comment]
значит неверно собрал сервер. крашей таких не наблюдается
